### ISSUE TITLE
E SIG: Failed to set thread affinity 0xff: error 1 every time I open RPCS3

### ISSUE THREAD

**Issue by gabriele2000** [Nightmayr-snaps/rpcs3-snap#10]

**Comment by Nightmayr** [comment]
I believe to solve this you'll need to enable the `process-control` permission for the snap. Can be done either through the snap store (Ubuntu software) or through the terminal, both methods are detailed below pick from whichever option you feel most comfortable with.

1) In Ubuntu Software navigate to the RPCS3 store page and click on the permissions button. Enable "Pause or end any process on the system"
2) In a terminal enter the command `snap connect rpcs3-emu:process-control`

Once you've enabled the permission, you should find that error is gone from the RPCS3 log

**Comment by Gdugas-prog** [comment]
your awesome !! thank you :-)
